import os
import json
import requests
from git import Repo
from dotenv import load_dotenv

load_dotenv()

class MonsterCore:
    def __init__(self):
        self.project_name = os.getenv("PROJECT_NAME", "Monster")
        self.project_id = os.getenv("PROJECT_ID", "525")
        self.deepseek_key = os.getenv("DEEPSEEK_API_KEY")
        
        self.repo_path = os.getcwd()
        try:
            self.repo = Repo(self.repo_path)
        except Exception:
            self.repo = None

    def feature_4_controller(self, user_input: str) -> dict:
        print(f"[{self.project_name}] Feature 4: Analyzing input and routing...")
        context = {
            "task_description": user_input,
            "status": "ready_for_planning"
        }
        return context

    def feature_1_mastermind(self, context: dict) -> dict:
        print(f"[{self.project_name}] Feature 1: Logical planning and code structuring...")
        if not self.deepseek_key:
            print(f"[{self.project_name}] Warning: DEEPSEEK_API_KEY missing. Using simulated plan.")
            return {"steps": ["init", "build", "test"], "architecture": "modular"}
        
        headers = {
            "Authorization": f"Bearer {self.deepseek_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": "deepseek-coder",
            "messages": [
                {"role": "system", "content": "You are Monster Feature 1. Plan the code structure."},
                {"role": "user", "content": context.get("task_description", "")}
            ]
        }
        
        try:
            response = requests.post("https://api.deepseek.com/v1/chat/completions", headers=headers, json=payload)
            response.raise_for_status()
            return response.json()
        except Exception as e:
            print(f"[{self.project_name}] API Error: {e}")
            return {"error": str(e)}

    def feature_2_executor(self, plan: dict) -> str:
        print(f"[{self.project_name}] Feature 2: Writing executable code...")
        
        if "error" in plan:
            return "# Error in planning phase. Code generation aborted.\n"
            
        generated_code = (
            "# Auto-generated by Monster AI (Feature 2)\n"
            "def execute_project():\n"
            "    print('System initialized and project built successfully.')\n\n"
            "if __name__ == '__main__':\n"
            "    execute_project()\n"
        )
        return generated_code

    def feature_3_storage(self, filename: str, code_content: str) -> bool:
        print(f"[{self.project_name}] Feature 3: Saving memory and creating Git checkpoint...")
        
        try:
            with open(filename, "w", encoding="utf-8") as file:
                file.write(code_content)
                
            if self.repo:
                self.repo.index.add([filename])
                self.repo.index.commit(f"Monster Auto-Checkpoint: Updated {filename}")
                print(f"[{self.project_name}] Feature 3: Checkpoint saved to Git.")
            else:
                print(f"[{self.project_name}] Feature 3: Saved locally (Git repo not detected).")
            return True
            
        except Exception as e:
            print(f"[{self.project_name}] Feature 3 Error: {e}")
            return False

    def execute_workflow(self, user_command: str):
        print(f"\n--- Starting {self.project_name} Workflow ---")
        
        context = self.feature_4_controller(user_command)
        plan = self.feature_1_mastermind(context)
        code = self.feature_2_executor(plan)
        
        output_file = "monster_output.py"
        self.feature_3_storage(output_file, code)
        
        print(f"--- {self.project_name} Workflow Completed ---\n")

if __name__ == "__main__":
    monster_agent = MonsterCore()
    test_command = "Build a basic python application"
    monster_agent.execute_workflow(test_command)
  
